# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: flake8 Lint

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
